apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- flux-system
- flux-system-automation.yaml
- kubecit-service-deployment.yaml
- kubecit-service-policy.yaml
- kubecit-service-registry.yaml
